version: '3'

services:
  nginx-rtmp-vod-ffmpeg:
      build:
        context: .

      restart: always
      container_name: nginx-rtmp-vod-ffmpeg

      volumes:
        - ./nginx.conf.webcam:/etc/nginx/nginx.conf

      ports:
        - "1935:1935"
        - "8080:8080"

      devices:
        - "/dev/video0:/dev/video0"